openapi: 3.0.3
info:
  title: AI Chat Interface API
  description: API for the AI Chat Interface feature
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server

paths:
  /auth/login:
    post:
      summary: User login
      description: Authenticate user and return access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: securepassword
              required:
                - email
                - password
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  token_type:
                    type: string
                    example: bearer
        '401':
          description: Invalid credentials

  /chats:
    get:
      summary: Get user's chat sessions
      description: Retrieve a list of all chat sessions for the authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of chat sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatSession'
        '401':
          description: Unauthorized
    post:
      summary: Create a new chat session
      description: Start a new conversation with the AI assistant
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                initial_message:
                  type: string
                  example: "Hello, can you help me with..."
              required:
                - initial_message
      responses:
        '201':
          description: New chat session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatSession'
        '401':
          description: Unauthorized
        '429':
          description: Rate limit exceeded (more than 500 requests per day)

  /chats/{chatId}:
    get:
      summary: Get chat session details
      description: Retrieve a specific chat session with its messages
      security:
        - bearerAuth: []
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier of the chat session
      responses:
        '200':
          description: Chat session details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatSessionWithMessages'
        '401':
          description: Unauthorized
        '404':
          description: Chat session not found
    delete:
      summary: Delete a chat session
      description: Remove a chat session and all its messages
      security:
        - bearerAuth: []
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier of the chat session
      responses:
        '204':
          description: Chat session deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Chat session not found

  /chats/{chatId}/messages:
    get:
      summary: Get messages in a chat session
      description: Retrieve all messages in a specific chat session
      security:
        - bearerAuth: []
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier of the chat session
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Maximum number of messages to return
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Number of messages to skip
      responses:
        '200':
          description: List of messages in the chat session
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
        '404':
          description: Chat session not found
    post:
      summary: Send a message in chat session
      description: Send a new message to the AI assistant in a specific chat session
      security:
        - bearerAuth: []
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier of the chat session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: "What can you help me with?"
              required:
                - content
      responses:
        '201':
          description: Message sent and response received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    $ref: '#/components/schemas/Message'
                  ai_response:
                    $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
        '404':
          description: Chat session not found
        '429':
          description: Rate limit exceeded (more than 500 requests per day)

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        email:
          type: string
          format: email
          example: user@example.com
        username:
          type: string
          example: johndoe
        created_at:
          type: string
          format: date-time
          example: "2025-11-06T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-11-06T10:00:00Z"
      required:
        - id
        - email
        - username
        - created_at
        - updated_at

    ChatSession:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174001"
        user_id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        title:
          type: string
          example: "How to implement React components?"
        created_at:
          type: string
          format: date-time
          example: "2025-11-06T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-11-06T10:00:00Z"
        is_active:
          type: boolean
          example: true
      required:
        - id
        - user_id
        - title
        - created_at
        - updated_at
        - is_active

    ChatSessionWithMessages:
      allOf:
        - $ref: '#/components/schemas/ChatSession'
        - type: object
          properties:
            messages:
              type: array
              items:
                $ref: '#/components/schemas/Message'

    Message:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174002"
        chat_session_id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174001"
        sender_type:
          type: string
          enum: [user, assistant]
          example: user
        content:
          type: string
          example: "What can you help me with?"
        created_at:
          type: string
          format: date-time
          example: "2025-11-06T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-11-06T10:00:00Z"
        sequence_number:
          type: integer
          example: 1
      required:
        - id
        - chat_session_id
        - sender_type
        - content
        - created_at
        - updated_at
        - sequence_number

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT